// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Molla.Data;

#nullable disable

namespace Molla.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230602190256_CreateAllTables")]
    partial class CreateAllTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Molla.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(4889),
                            Description = "Phasellus hendrerit. Pellentesque aliquet nibh nec urna. In nisi neque, aliquet vel, dapibus id, mattis vel, nisi. Sed pretium, ligula sollicitudin laoreet viverra, tortor libero sodales leo, eget blandit nunc tortor eu nibh ...",
                            Image = "blog-bigP-1.jpeg",
                            Name = "Sed adipiscing ornare",
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(4902),
                            Description = "Phasellus hendrerit. Pellentesque aliquet nibh nec urna. In nisi neque, aliquet vel, dapibus id, mattis vel, nisi. Sed pretium, ligula sollicitudin laoreet viverra, tortor libero sodales leo, eget blandit nunc tortor eu nibh ...",
                            Image = "blog-bigP-2.jpeg",
                            Name = "Sed adipiscing ornare",
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(4903),
                            Description = "Phasellus hendrerit. Pellentesque aliquet nibh nec urna. In nisi neque, aliquet vel, dapibus id, mattis vel, nisi. Sed pretium, ligula sollicitudin laoreet viverra, tortor libero sodales leo, eget blandit nunc tortor eu nibh ...",
                            Image = "blog-bigP-3.jpeg",
                            Name = "Sed adipiscing ornare",
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(4903),
                            Description = "Phasellus hendrerit. Pellentesque aliquet nibh nec urna. In nisi neque, aliquet vel, dapibus id, mattis vel, nisi. Sed pretium, ligula sollicitudin laoreet viverra, tortor libero sodales leo, eget blandit nunc tortor eu nibh ...",
                            Image = "blog-bigP-4.jpeg",
                            Name = "Sed adipiscing ornare",
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(4904),
                            Description = "Phasellus hendrerit. Pellentesque aliquet nibh nec urna. In nisi neque, aliquet vel, dapibus id, mattis vel, nisi. Sed pretium, ligula sollicitudin laoreet viverra, tortor libero sodales leo, eget blandit nunc tortor eu nibh ...",
                            Image = "blog-bigP-5.jpeg",
                            Name = "Sed adipiscing ornare",
                            SoftDelete = false
                        });
                });

            modelBuilder.Entity("Molla.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(4998),
                            Icon = "brand1.png",
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(4999),
                            Icon = "brand2.png",
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5000),
                            Icon = "brand3.png",
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5000),
                            Icon = "brand4.png",
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5001),
                            Icon = "brand5.png",
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5001),
                            Icon = "brand6.png",
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5002),
                            Icon = "brand7.png",
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5002),
                            Icon = "brand8.png",
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 9,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5003),
                            Icon = "brand9.png",
                            SoftDelete = false
                        });
                });

            modelBuilder.Entity("Molla.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5016),
                            Name = "Electronics",
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5017),
                            Name = "Gift Ideas",
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5017),
                            Name = "Beds",
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5018),
                            Name = "Lighting",
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5018),
                            Name = "Sofas & Sleeper sofas",
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5019),
                            Name = "Storage",
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5019),
                            Name = "Armchairs & Chaises",
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5020),
                            Name = "Decoration",
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 9,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5020),
                            Name = "Kitchen Cabinets",
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 10,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5021),
                            Name = "Coffee & Tables",
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 11,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5021),
                            Name = "Outdoor Furniture",
                            SoftDelete = false
                        });
                });

            modelBuilder.Entity("Molla.Models.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5030),
                            Name = "Blue",
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5031),
                            Name = "Black",
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5031),
                            Name = "White",
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5032),
                            Name = "Red",
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5032),
                            Name = "Yellow",
                            SoftDelete = false
                        });
                });

            modelBuilder.Entity("Molla.Models.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Percent")
                        .HasColumnType("tinyint");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Discounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5041),
                            Name = "Black Friday",
                            Percent = (byte)70,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5042),
                            Name = "Spring Discount",
                            Percent = (byte)50,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5042),
                            Name = "No Discount",
                            Percent = (byte)0,
                            SoftDelete = false
                        });
                });

            modelBuilder.Entity("Molla.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DiscountId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("SellCount")
                        .HasColumnType("int");

                    b.Property<int>("SizeId")
                        .HasColumnType("int");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ColorId");

                    b.HasIndex("DiscountId");

                    b.HasIndex("SizeId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            ColorId = 2,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5059),
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque",
                            DiscountId = 3,
                            Name = "Apple MacBook Pro 14 MPHK3RU/A Silver",
                            Price = 7489m,
                            Rating = 5,
                            SellCount = 20000,
                            SizeId = 3,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            ColorId = 3,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5062),
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque",
                            DiscountId = 3,
                            Name = "iPhone 14 Pro 256 GB Deep Purple",
                            Price = 3149m,
                            Rating = 3,
                            SellCount = 2500,
                            SizeId = 3,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            ColorId = 2,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5064),
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque",
                            DiscountId = 2,
                            Name = "2E Gaming Set of wheels Clear / 2E-GWH-002-CL",
                            Price = 49m,
                            Rating = 2,
                            SellCount = 100,
                            SizeId = 2,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            ColorId = 1,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5065),
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque",
                            DiscountId = 1,
                            Name = "Gaming Floor Mat Canyon Camouflage / CND-SFM02",
                            Price = 79m,
                            Rating = 1,
                            SellCount = 100,
                            SizeId = 1,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            ColorId = 5,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5066),
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque",
                            DiscountId = 3,
                            Name = "Gala Wood",
                            Price = 4899m,
                            Rating = 5,
                            SellCount = 900,
                            SizeId = 3,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            ColorId = 4,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5067),
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque",
                            DiscountId = 3,
                            Name = "İmfa Viva",
                            Price = 2599m,
                            Rating = 4,
                            SellCount = 800,
                            SizeId = 3,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            ColorId = 3,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5090),
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque",
                            DiscountId = 3,
                            Name = "Beurer SL10",
                            Price = 79m,
                            Rating = 3,
                            SellCount = 2600,
                            SizeId = 3,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            ColorId = 2,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5091),
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque",
                            DiscountId = 2,
                            Name = "Smart Solar",
                            Price = 79m,
                            Rating = 2,
                            SellCount = 20,
                            SizeId = 2,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            ColorId = 1,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5092),
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque",
                            DiscountId = 1,
                            Name = "Gala Astana",
                            Price = 2999m,
                            Rating = 1,
                            SellCount = 4200,
                            SizeId = 1,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            ColorId = 5,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5093),
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque",
                            DiscountId = 3,
                            Name = "Alzzoni Paris",
                            Price = 2249m,
                            Rating = 5,
                            SellCount = 2000,
                            SizeId = 3,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 6,
                            ColorId = 4,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5094),
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque",
                            DiscountId = 3,
                            Name = "Tramontina Food Storage",
                            Price = 33m,
                            Rating = 4,
                            SellCount = 500,
                            SizeId = 3,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 6,
                            ColorId = 3,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5095),
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque",
                            DiscountId = 3,
                            Name = "Car Storage",
                            Price = 22m,
                            Rating = 3,
                            SellCount = 6200,
                            SizeId = 3,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 7,
                            ColorId = 2,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5096),
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque",
                            DiscountId = 2,
                            Name = "CAM Scudo 166",
                            Price = 749m,
                            Rating = 2,
                            SellCount = 1200,
                            SizeId = 2,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 7,
                            ColorId = 1,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5097),
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque",
                            DiscountId = 1,
                            Name = "Softaç Art",
                            Price = 539m,
                            Rating = 1,
                            SellCount = 4200,
                            SizeId = 1,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 8,
                            ColorId = 5,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5098),
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque",
                            DiscountId = 3,
                            Name = "Chicco",
                            Price = 69m,
                            Rating = 5,
                            SellCount = 1000,
                            SizeId = 3,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 8,
                            ColorId = 4,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5099),
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque",
                            DiscountId = 3,
                            Name = "Hape",
                            Price = 129m,
                            Rating = 4,
                            SellCount = 2100,
                            SizeId = 3,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 9,
                            ColorId = 3,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5100),
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque",
                            DiscountId = 3,
                            Name = "La Sommeliere ",
                            Price = 2199m,
                            Rating = 3,
                            SellCount = 2300,
                            SizeId = 3,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 9,
                            ColorId = 2,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5102),
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque",
                            DiscountId = 2,
                            Name = "Pozis FH",
                            Price = 899m,
                            Rating = 2,
                            SellCount = 200,
                            SizeId = 2,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 10,
                            ColorId = 1,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5103),
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque",
                            DiscountId = 1,
                            Name = "AEG KKK994500T",
                            Price = 7199m,
                            Rating = 1,
                            SellCount = 240,
                            SizeId = 1,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 10,
                            ColorId = 2,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5104),
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque",
                            DiscountId = 2,
                            Name = "Philips EP2236/40",
                            Price = 1699m,
                            Rating = 3,
                            SellCount = 2000,
                            SizeId = 3,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 11,
                            ColorId = 2,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5105),
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque",
                            DiscountId = 3,
                            Name = "Karcher K5 EU",
                            Price = 1059m,
                            Rating = 5,
                            SellCount = 270,
                            SizeId = 2,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 11,
                            ColorId = 2,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5106),
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque",
                            DiscountId = 3,
                            Name = "Total TGT11276/3000w",
                            Price = 2299m,
                            Rating = 5,
                            SellCount = 500,
                            SizeId = 1,
                            SoftDelete = false
                        });
                });

            modelBuilder.Entity("Molla.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5119),
                            Image = "notebook.png",
                            IsMain = true,
                            ProductId = 1,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5120),
                            Image = "notebook2.png",
                            IsMain = false,
                            ProductId = 1,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5121),
                            Image = "phone.png",
                            IsMain = true,
                            ProductId = 1,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5121),
                            Image = "phone2.png",
                            IsMain = false,
                            ProductId = 1,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5122),
                            Image = "canyon2.png",
                            IsMain = true,
                            ProductId = 2,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5122),
                            Image = "gift2.png",
                            IsMain = true,
                            ProductId = 2,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5123),
                            Image = "beds.png",
                            IsMain = true,
                            ProductId = 3,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5124),
                            Image = "beds1.png",
                            IsMain = false,
                            ProductId = 3,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 9,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5124),
                            Image = "beds2.png",
                            IsMain = true,
                            ProductId = 3,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 10,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5125),
                            Image = "beds3.png",
                            IsMain = false,
                            ProductId = 3,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 11,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5126),
                            Image = "light.png",
                            IsMain = true,
                            ProductId = 4,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 12,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5126),
                            Image = "light2.png",
                            IsMain = false,
                            ProductId = 4,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 13,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5128),
                            Image = "light4.png",
                            IsMain = true,
                            ProductId = 4,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 14,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5129),
                            Image = "sofa.png",
                            IsMain = true,
                            ProductId = 5,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 15,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5130),
                            Image = "sofa2.png",
                            IsMain = true,
                            ProductId = 5,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 16,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5131),
                            Image = "storage.png",
                            IsMain = true,
                            ProductId = 6,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 17,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5131),
                            Image = "storage2.png",
                            IsMain = false,
                            ProductId = 6,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 18,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5132),
                            Image = "stroge.png",
                            IsMain = true,
                            ProductId = 6,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 19,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5132),
                            Image = "chair2.png",
                            IsMain = true,
                            ProductId = 7,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 20,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5133),
                            Image = "chair3.png",
                            IsMain = false,
                            ProductId = 7,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 21,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5133),
                            Image = "chair1.png",
                            IsMain = true,
                            ProductId = 7,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 22,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5134),
                            Image = "decor.png",
                            IsMain = true,
                            ProductId = 8,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 23,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5135),
                            Image = "decor2.png",
                            IsMain = false,
                            ProductId = 8,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 24,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5135),
                            Image = "decor3.png",
                            IsMain = true,
                            ProductId = 8,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 25,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5136),
                            Image = "decor4.png",
                            IsMain = false,
                            ProductId = 8,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 26,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5136),
                            Image = "kitchen.png",
                            IsMain = true,
                            ProductId = 9,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 27,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5137),
                            Image = "kitchen2.png",
                            IsMain = false,
                            ProductId = 9,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 28,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5137),
                            Image = "kitchen3.png",
                            IsMain = true,
                            ProductId = 9,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 29,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5138),
                            Image = "kitchen4.png",
                            IsMain = false,
                            ProductId = 9,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 30,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5138),
                            Image = "coffee.png",
                            IsMain = true,
                            ProductId = 10,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 31,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5139),
                            Image = "coffee2.png",
                            IsMain = true,
                            ProductId = 10,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 32,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5140),
                            Image = "coffee3.png",
                            IsMain = false,
                            ProductId = 10,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 33,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5140),
                            Image = "outdoor.png",
                            IsMain = true,
                            ProductId = 11,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 34,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5141),
                            Image = "outdoor3.png",
                            IsMain = true,
                            ProductId = 11,
                            SoftDelete = false
                        });
                });

            modelBuilder.Entity("Molla.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5154),
                            Description = "orders $50 or more",
                            Name = "Free Shipping",
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5155),
                            Description = "within 30 days",
                            Name = "Free Returns",
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5155),
                            Description = "When you sign up",
                            Name = "Get 20% Off 1 Item",
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5156),
                            Description = "24/7 amazing services",
                            Name = "We Support",
                            SoftDelete = false
                        });
                });

            modelBuilder.Entity("Molla.Models.Size", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Sizes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5050),
                            Name = "Small",
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5051),
                            Name = "Medium",
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5052),
                            Name = "Large",
                            SoftDelete = false
                        });
                });

            modelBuilder.Entity("Molla.Models.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Sliders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5167),
                            Image = "slider-1.jpeg",
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5168),
                            Image = "slider-2.jpeg",
                            SoftDelete = false
                        });
                });

            modelBuilder.Entity("Molla.Models.SliderInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SliderInfos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5176),
                            Description = "Airpods Earphones",
                            SoftDelete = false,
                            Title = "Daily Deals"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5177),
                            Description = "Echo Dot 3rd Gen",
                            SoftDelete = false,
                            Title = "Deals and Promotions"
                        });
                });

            modelBuilder.Entity("Molla.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5185),
                            Image = "member-1.jpg",
                            Name = "Samanta Grey",
                            Position = "Founder & CEO",
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5186),
                            Image = "member-3.jpg",
                            Name = "Janet Joy",
                            Position = "Product Manager",
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2023, 6, 2, 23, 2, 56, 609, DateTimeKind.Local).AddTicks(5187),
                            Image = "member-2.jpg",
                            Name = "Bruce Sutton",
                            Position = "Sales & Marketing Manager",
                            SoftDelete = false
                        });
                });

            modelBuilder.Entity("Molla.Models.Product", b =>
                {
                    b.HasOne("Molla.Models.Category", "Category")
                        .WithMany("Product")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Molla.Models.Color", "Color")
                        .WithMany("Products")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Molla.Models.Discount", "Discount")
                        .WithMany("Product")
                        .HasForeignKey("DiscountId");

                    b.HasOne("Molla.Models.Size", "Size")
                        .WithMany("Products")
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Color");

                    b.Navigation("Discount");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("Molla.Models.ProductImage", b =>
                {
                    b.HasOne("Molla.Models.Product", "Product")
                        .WithMany("ProductImage")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Molla.Models.Category", b =>
                {
                    b.Navigation("Product");
                });

            modelBuilder.Entity("Molla.Models.Color", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Molla.Models.Discount", b =>
                {
                    b.Navigation("Product");
                });

            modelBuilder.Entity("Molla.Models.Product", b =>
                {
                    b.Navigation("ProductImage");
                });

            modelBuilder.Entity("Molla.Models.Size", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
